export type Poem = {
  es: string;
  en: string;
  author: string;
  source?: string;
};

export const POEMS: Poem[] = [
  // ── Pablo Neruda ────────────────────────────────────────────────────────────
  { es: "Te amo como se aman ciertas cosas oscuras, secretamente, entre la sombra y el alma.", en: "I love you as certain dark things are loved, secretly, between the shadow and the soul.", author: "Pablo Neruda", source: "Soneto XVII" },
  { es: "Es tan corto el amor, y es tan largo el olvido.", en: "Love is so short, forgetting is so long.", author: "Pablo Neruda", source: "Poema 20" },
  { es: "Quiero hacer contigo lo que la primavera hace con los cerezos.", en: "I want to do with you what spring does with the cherry trees.", author: "Pablo Neruda", source: "Poema XIII" },
  { es: "Puedo escribir los versos más tristes esta noche. La quise, y a veces ella también me quería.", en: "Tonight I can write the saddest lines. I loved her, and sometimes she loved me too.", author: "Pablo Neruda", source: "Poema 20" },
  { es: "Si tú me olvidas, quiero que tú sepas una cosa: ya sabes cómo es esto, si miro la luna de cristal, la rama roja del lento otoño en mi ventana, todo me lleva a ti.", en: "If you forget me, I want you to know one thing: you know how it is: if I look at the crystal moon, at the red branch of the slow autumn, everything carries me to you.", author: "Pablo Neruda", source: "Si tú me olvidas" },
  { es: "No te quiero sino porque te quiero, y de quererte a no quererte llego.", en: "I do not love you except because I love you, and from loving you to not loving you I go.", author: "Pablo Neruda", source: "Soneto XLIV" },
  { es: "Nuestro amor no es cosa de flores sino de lava y de roca.", en: "Our love is not a thing of flowers but of lava and rock.", author: "Pablo Neruda", source: "Cien Sonetos de Amor" },
  { es: "Amo el amor de los marineros que besan y se van.", en: "I love the love of sailors who kiss and go away.", author: "Pablo Neruda", source: "Poema XIV" },
  { es: "Yo quiero hacer contigo lo que la noche hace con la sombra: besarte.", en: "I want to do with you what the night does with shadow: kiss you.", author: "Pablo Neruda", source: "Veinte Poemas de Amor" },
  { es: "Traspasado, lejos, voy cerrando mis heridas, voy cerrando mi amor.", en: "Pierced, far away, I go closing my wounds, I go closing my love.", author: "Pablo Neruda", source: "Poema 20" },
  { es: "Amor, cuántos caminos hasta llegar a un beso.", en: "Love, how many roads until a kiss is reached.", author: "Pablo Neruda", source: "Soneto LXIX" },
  { es: "Mi cuerpo de labriego salvaje te socava y hace saltar el hijo del fondo de la tierra.", en: "My body of a wild peasant undermines you and makes the child leap from the depths of the earth.", author: "Pablo Neruda", source: "Poema XII" },
  { es: "Nosotros, los de entonces, ya no somos los mismos.", en: "We, of that time, are no longer the same.", author: "Pablo Neruda", source: "Poema 20" },
  { es: "No te quiero para que llenes mi soledad, sino para que la vacíes.", en: "I don't love you to fill my solitude, but to empty it.", author: "Pablo Neruda", source: "Libro de las Preguntas" },
  { es: "Hay algo de pájaro en el amor que huye, algo de germen, de llama, de niño.", en: "There is something of bird in love that flees, something of germ, of flame, of child.", author: "Pablo Neruda", source: "Cien Sonetos de Amor" },
  { es: "Te recuerdo como eras en el último otoño. Eras la boina gris y el corazón en calma.", en: "I remember you as you were in the last autumn. You were the grey beret and the still heart.", author: "Pablo Neruda", source: "Poema VI" },
  { es: "Amándote, mi vida se llenó de luz.", en: "Loving you, my life filled with light.", author: "Pablo Neruda", source: "Cien Sonetos de Amor" },

  // ── Gustavo Adolfo Bécquer ───────────────────────────────────────────────────
  { es: "Podrá nublarse el sol eternamente; podrá secarse en un instante el mar; podrá romperse el eje de la tierra como un débil cristal: ¡todo sucederá! Pero jamás en mí podrá apagarse la llama de tu amor.", en: "The sun may cloud forever; the sea may dry in an instant; the earth's axis may shatter like fragile glass — but never in me shall the flame of your love be quenched.", author: "Gustavo Adolfo Bécquer", source: "Rima LIII" },
  { es: "Hoy como ayer, mañana como hoy, ¡y siempre igual! Un día más de vida en mi agonia.", en: "Today as yesterday, tomorrow as today, and always the same! One more day of life in my agony.", author: "Gustavo Adolfo Bécquer", source: "Rima LXVI" },
  { es: "¿Qué es poesía? dices mientras clavas en mi pupila tu pupila azul. ¡Qué es poesía! ¿Y tú me lo preguntas? Poesía eres tú.", en: "'What is poetry?' you ask, fixing your blue pupil on mine. 'What is poetry?' And you ask me that? Poetry is you.", author: "Gustavo Adolfo Bécquer", source: "Rima XXI" },
  { es: "Cuando miro el azul horizonte perderse a lo lejos, las brumas de la tarde desvanecerse, siento que mi alma también quiere perderse en ti.", en: "When I watch the blue horizon fade in the distance, the evening mists dissolve, I feel my soul also wants to lose itself in you.", author: "Gustavo Adolfo Bécquer", source: "Rima XXIV" },
  { es: "Yo soy ardiente, yo soy morena, yo soy el símbolo de la pasión.", en: "I am ardent, I am dark, I am the symbol of passion.", author: "Gustavo Adolfo Bécquer", source: "Rima XI" },
  { es: "Tu pupila es azul, y cuando ríes, su claridad suave me recuerda el temblor de la onda que en el mar luminoso muere.", en: "Your pupil is blue, and when you laugh, its soft brightness reminds me of the trembling of the wave that dies on the luminous sea.", author: "Gustavo Adolfo Bécquer", source: "Rima XIII" },
  { es: "Volverán las oscuras golondrinas en tu balcón sus nidos a colgar, y otra vez con el ala a sus cristales jugando llamarán.", en: "The dark swallows will return to hang their nests on your balcony, and once again with their wings they will play against your windows.", author: "Gustavo Adolfo Bécquer", source: "Rima LIII" },
  { es: "Del salón en el ángulo oscuro, de su dueña tal vez olvidada, silenciosa y cubierta de polvo, veíase el arpa.", en: "In the dark corner of the parlor, perhaps forgotten by its mistress, silent and covered with dust, the harp could be seen.", author: "Gustavo Adolfo Bécquer", source: "Rima VII" },

  // ── Sor Juana Inés de la Cruz ────────────────────────────────────────────────
  { es: "Esta tarde, mi bien, cuando te hablaba, como en tu rostro y tus acciones vía que con palabras no te persuadía, que el corazón me vieses deseaba.", en: "This evening, my love, as I spoke to you, seeing in your face and gestures that words could not persuade you, I wished that you might see my heart.", author: "Sor Juana Inés de la Cruz", source: "Soneto 165" },
  { es: "Hombres necios que acusáis a la mujer sin razón, sin ver que sois la ocasión de lo mismo que culpáis.", en: "Foolish men who accuse women without reason, not seeing that you yourselves are the cause of what you blame.", author: "Sor Juana Inés de la Cruz", source: "Redondillas" },
  { es: "En perseguirme, Mundo, ¿qué interesas? ¿En qué te ofendo cuando sólo intento poner bellezas en mi entendimiento?", en: "In pursuing me, O World, what is your interest? How do I offend you when my only intent is to put beauty in my understanding?", author: "Sor Juana Inés de la Cruz", source: "Soneto 146" },
  { es: "Detente, sombra de mi bien esquivo, imagen del hechizo que más quiero.", en: "Stay, shadow of my elusive love, image of the enchantment I desire most.", author: "Sor Juana Inés de la Cruz", source: "Soneto 147" },
  { es: "Amor empieza por desasosiego, solicitud, ardores y desvelos.", en: "Love begins with unease, longing, burning desire and sleeplessness.", author: "Sor Juana Inés de la Cruz", source: "Soneto 148" },

  // ── Mario Benedetti ─────────────────────────────────────────────────────────
  { es: "Te quiero porque tus manos trabajan por la justicia.", en: "I love you because your hands work for justice.", author: "Mario Benedetti", source: "Te Quiero" },
  { es: "Cuando te tengo a ti vida, cuánta vida me debes; cuando no te tengo a ti, nada me debes.", en: "When I have you, life, how much life you owe me; when I do not have you, you owe me nothing.", author: "Mario Benedetti", source: "Inventario" },
  { es: "No te rindas, aún estás a tiempo de alcanzar y comenzar de nuevo.", en: "Do not give in, you still have time to reach out and start anew.", author: "Mario Benedetti", source: "No te Rindas" },
  { es: "Mi táctica es hablarte y escucharte, construir con palabras un puente indestructible.", en: "My tactic is to speak to you and listen to you, to build with words an indestructible bridge.", author: "Mario Benedetti", source: "Táctica y Estrategia" },
  { es: "Mi estrategia es quedarme en tu recuerdo, no sé cómo ni sé con qué pretexto.", en: "My strategy is to remain in your memory — I do not know how, nor with what pretext.", author: "Mario Benedetti", source: "Táctica y Estrategia" },
  { es: "El amor que no muere es aquel que elige el silencio como lenguaje.", en: "The love that does not die is the one that chooses silence as its language.", author: "Mario Benedetti", source: "La Vida ese Paréntesis" },
  { es: "Contigo aprendo a querer lo que siempre quise querer.", en: "With you I learn to love what I always wanted to love.", author: "Mario Benedetti", source: "Inventario" },
  { es: "Será porque tu amor es el único lugar donde me resulta fácil ser feliz.", en: "Perhaps it is because your love is the only place where it is easy for me to be happy.", author: "Mario Benedetti", source: "La Vida ese Paréntesis" },

  // ── Federico García Lorca ────────────────────────────────────────────────────
  { es: "Verde que te quiero verde. Verde viento. Verdes ramas.", en: "Green, how I love you green. Green wind. Green branches.", author: "Federico García Lorca", source: "Romance Sonámbulo" },
  { es: "Tengo miedo a perder la maravilla de tus ojos de estatua y el acento que de noche me pone en la mejilla la solitaria rosa de tu aliento.", en: "I fear to lose the wonder of your statue eyes and the cadence that at night places on my cheek the solitary rose of your breath.", author: "Federico García Lorca", source: "Soneto de la Dulce Queja" },
  { es: "¿Quién te desnuda el cuerpo del mar? La luna, la luna.", en: "Who undresses your body from the sea? The moon, the moon.", author: "Federico García Lorca", source: "Diván del Tamarit" },
  { es: "Tu vientre es una lucha de raíces, tus labios son un alba sin contorno.", en: "Your belly is a struggle of roots, your lips a borderless dawn.", author: "Federico García Lorca", source: "Soneto Gongorino" },
  { es: "Ay, qué trabajo me cuesta quererte como te quiero.", en: "Oh, what an effort it costs me to love you as I love you.", author: "Federico García Lorca", source: "Gacela del Amor Desesperado" },
  { es: "No hay noche que al acostarse no sepa que no te verá.", en: "There is no night when one lies down that does not know it will not see you again.", author: "Federico García Lorca", source: "Poema del Cante Jondo" },
  { es: "La luna puso en el río, la luna llena, un pabellón de sombra y un sueño de plata.", en: "The moon placed on the river, the full moon, a pavilion of shadow and a dream of silver.", author: "Federico García Lorca", source: "Romancero Gitano" },

  // ── Alfonsina Storni ─────────────────────────────────────────────────────────
  { es: "Hoy te miré de frente y supe que en mis venas corre tu nombre lentamente.", en: "Today I looked at you face to face and knew that in my veins your name runs slowly.", author: "Alfonsina Storni", source: "El Dulce Daño" },
  { es: "Voy a dormir, nodriza mía, acuéstame. Ponme una lámpara a la cabecera; una constelación; la que te guste.", en: "I am going to sleep, my nurse, lay me down. Place a lamp at my bedside; a constellation; whichever you like.", author: "Alfonsina Storni", source: "Voy a Dormir" },
  { es: "Quiero dormir el sueño de las manzanas, alejarme del tumulto de los cementerios.", en: "I want to sleep the sleep of apples, to move away from the tumult of cemeteries.", author: "Alfonsina Storni", source: "Voy a Dormir" },
  { es: "Eres el mar que toca mi orilla y se retira.", en: "You are the sea that touches my shore and withdraws.", author: "Alfonsina Storni", source: "Irremediablemente" },
  { es: "Mi cuerpo es un poema que nadie sabe leer.", en: "My body is a poem that no one knows how to read.", author: "Alfonsina Storni", source: "Mascarilla y Trébol" },
  { es: "Se me va de los dedos la caricia sin rumbo. Yo no sé por qué ríes si estás sola.", en: "The aimless caress slips from my fingers. I do not know why you laugh if you are alone.", author: "Alfonsina Storni", source: "El Dulce Daño" },

  // ── Octavio Paz ──────────────────────────────────────────────────────────────
  { es: "Tuve sed y tú fuiste para mí agua bajo la sombra de un árbol.", en: "I was thirsty and you were water for me beneath the shade of a tree.", author: "Octavio Paz", source: "Piedra de Sol" },
  { es: "Amar es combatir, es abrir puertas, dejar de ser fantasma con un número a perpetua cadena condenado.", en: "To love is to battle, to open doors, to cease being a ghost condemned to a perpetual chain of numbers.", author: "Octavio Paz", source: "Piedra de Sol" },
  { es: "El amor es una mirada sobre el tiempo. No somos siempre los mismos, pero siempre nos reconocemos.", en: "Love is a gaze upon time. We are not always the same, but we always recognize each other.", author: "Octavio Paz", source: "El Laberinto de la Soledad" },
  { es: "Dos cuerpos frente a frente son a veces dos olas y la noche es océano.", en: "Two bodies face to face are sometimes two waves and the night is ocean.", author: "Octavio Paz", source: "Dos Cuerpos" },
  { es: "Tocarte es conocerte y conocerte es conocerme.", en: "To touch you is to know you and to know you is to know myself.", author: "Octavio Paz", source: "Piedra de Sol" },
  { es: "Entre tus piernas hay un precipicio adonde llueve el tiempo.", en: "Between your legs there is a precipice where time rains down.", author: "Octavio Paz", source: "Piedra de Sol" },

  // ── Gabriela Mistral ─────────────────────────────────────────────────────────
  { es: "Yo no tengo soledad, es mi amado todo: duerme bajo una cubierta de estrella destellando.", en: "I am not alone — my beloved is everything: he sleeps beneath a blanket of glittering stars.", author: "Gabriela Mistral", source: "Desolación" },
  { es: "Me besó y ahora soy otra; soy como tierra que tiene semilla y es primavera entera.", en: "He kissed me and now I am another; I am like earth that holds a seed and is entirely spring.", author: "Gabriela Mistral", source: "Desolación" },
  { es: "El amor que callé llenará la muerte: ¡tú lo oirás, grave, sin asombro.", en: "The love I kept silent will fill death: you will hear it, grave, without wonder.", author: "Gabriela Mistral", source: "Lagar" },
  { es: "La tierra no entiende que llamemos amor a la sed que se apaga con solo mirar.", en: "The earth does not understand that we call love the thirst that is quenched by merely looking.", author: "Gabriela Mistral", source: "Ternura" },
  { es: "Piececitos de niño, azulosos de frío, ¡cómo os ven y no os cubren, Dios mío!", en: "Little feet of a child, blue with cold — how they see you and do not cover you, my God!", author: "Gabriela Mistral", source: "Ternura" },
  { es: "Bésame con el beso estrictamente de tu boca, que es tuyo y es mío.", en: "Kiss me with the purely exact kiss of your mouth, which is yours and mine.", author: "Gabriela Mistral", source: "Desolación" },

  // ── Rubén Darío ──────────────────────────────────────────────────────────────
  { es: "Ama tu ritmo y ritma tus acciones bajo su ley, así como tus versos.", en: "Love your rhythm and rhythm your actions under its law, as you do your verses.", author: "Rubén Darío", source: "Prosas Profanas" },
  { es: "Juventud, divino tesoro, ¡ya te vas para no volver! Cuando quiero llorar, no lloro, y a veces lloro sin querer.", en: "Youth, divine treasure, you leave and do not return! When I want to weep, I weep not, and sometimes I weep without wishing.", author: "Rubén Darío", source: "Canción de Otoño en Primavera" },
  { es: "Yo soy aquel que ayer no más decía el verso azul y la canción profana.", en: "I am the one who only yesterday spoke of the blue verse and the profane song.", author: "Rubén Darío", source: "Cantos de Vida y Esperanza" },
  { es: "¡Carne, celeste carne de la mujer! Arcilla — dijo Hugo — ¡ambrosía más bien!", en: "Flesh, celestial flesh of woman! Clay — said Hugo — ambrosia rather!", author: "Rubén Darío", source: "Prosas Profanas" },
  { es: "La vida es dura. Amarga y pesa. ¡Ya no hay princesas que corten rosas!", en: "Life is hard. Bitter and heavy. There are no more princesses to cut roses!", author: "Rubén Darío", source: "Lo Fatal" },

  // ── César Vallejo ────────────────────────────────────────────────────────────
  { es: "Hay golpes en la vida, tan fuertes... ¡Yo no sé! Golpes como del odio de Dios.", en: "There are blows in life so violent — I don't know! Blows as from the hatred of God.", author: "César Vallejo", source: "Los Heraldos Negros" },
  { es: "Me moriré en París con aguacero, un día del cual tengo ya el recuerdo.", en: "I will die in Paris — in a downpour — on a day I already remember.", author: "César Vallejo", source: "Piedra Negra sobre una Piedra Blanca" },
  { es: "Amor, si muero y no me matas, ¿quién te dará la mano?", en: "Love, if I die and you do not kill me, who will give you a hand?", author: "César Vallejo", source: "Trilce" },
  { es: "Quisiera hoy ser feliz de buena gana, pero el famélico invierno me ha cogido el gusto.", en: "I would like to be happy today, freely, but the famished winter has taken my taste for it.", author: "César Vallejo", source: "Los Heraldos Negros" },
  { es: "Y si después de tantas palabras, no sobrevive la palabra.", en: "And if after so many words, the word does not survive.", author: "César Vallejo", source: "Poemas Humanos" },

  // ── Juana de Ibarbourou ──────────────────────────────────────────────────────
  { es: "Tómame ahora que aún es temprano y que llevo dalias nuevas en la mano.", en: "Take me now while it is still early and I carry new dahlias in my hand.", author: "Juana de Ibarbourou", source: "La Rosa de los Vientos" },
  { es: "Soy tuya en la carne y en el alma, como la ola es del mar profundo.", en: "I am yours in flesh and soul, as the wave belongs to the deep sea.", author: "Juana de Ibarbourou", source: "Las Lenguas de Diamante" },
  { es: "Si quieres, te daré la luna sobre el agua y los pájaros de la selva al amanecer.", en: "If you wish, I will give you the moon on the water and the birds of the forest at dawn.", author: "Juana de Ibarbourou", source: "Raíz Salvaje" },
  { es: "Sé que soy tuya como el río es del mar: porque el mar llama siempre y el río siempre va.", en: "I know I am yours as the river belongs to the sea: because the sea always calls and the river always goes.", author: "Juana de Ibarbourou", source: "Las Lenguas de Diamante" },
  { es: "La vida está aquí, en esta mano abierta que sostiene el sol.", en: "Life is here, in this open hand that holds the sun.", author: "Juana de Ibarbourou", source: "Raíz Salvaje" },

  // ── Rosario Castellanos ──────────────────────────────────────────────────────
  { es: "¿Y si habláramos el mismo idioma? Entonces aprendería a decir tu nombre.", en: "And if we spoke the same language? Then I would learn to say your name.", author: "Rosario Castellanos", source: "Poesía No Eres Tú" },
  { es: "El amor, esa monstruosa criatura, esa fiebre que quema y no consume.", en: "Love, that monstrous creature, that fever that burns and does not consume.", author: "Rosario Castellanos", source: "Poesía No Eres Tú" },
  { es: "Vivir es esto: morir despacio en los brazos de quien amamos.", en: "Living is this: dying slowly in the arms of those we love.", author: "Rosario Castellanos", source: "Poesía No Eres Tú" },
  { es: "El amor es un diálogo que no alcanza nunca su final.", en: "Love is a dialogue that never reaches its end.", author: "Rosario Castellanos", source: "Meditación en el Umbral" },

  // ── Idea Vilariño ────────────────────────────────────────────────────────────
  { es: "Ya no será, ya no. No viviremos juntos. No criaré a tu hijo. No coseré tu ropa. No te tendré de noche.", en: "It will not be, no more. We won't live together. I won't raise your child. I won't sew your clothes. I won't have you at night.", author: "Idea Vilariño", source: "Ya No" },
  { es: "Pasé tantos días deseándote que ya no recuerdo cómo era no quererte.", en: "I spent so many days wanting you that I no longer remember what it was like not to love you.", author: "Idea Vilariño", source: "Poemas de Amor" },
  { es: "Amor, amor, cuánta sed de ti tengo.", en: "Love, love, how much thirst I have for you.", author: "Idea Vilariño", source: "Poemas de Amor" },
  { es: "Se quedó en mi cuerpo tu aroma como queda en la copa el vino.", en: "Your scent remained in my body as wine remains in the glass.", author: "Idea Vilariño", source: "Poemas de Amor" },

  // ── José Martí ───────────────────────────────────────────────────────────────
  { es: "Yo soy un hombre sincero de donde crece la palma.", en: "I am a sincere man from where the palm tree grows.", author: "José Martí", source: "Versos Sencillos I" },
  { es: "Cultivo una rosa blanca en junio como en enero, para el amigo sincero que me da su mano franca.", en: "I cultivate a white rose in June as in January, for the sincere friend who offers me his open hand.", author: "José Martí", source: "Versos Sencillos XXXIX" },
  { es: "Con los pobres de la tierra quiero yo mi suerte echar.", en: "With the poor of the earth I want to cast my lot.", author: "José Martí", source: "Versos Sencillos I" },
  { es: "Amor sin medida, y duda sin medida — así se vive.", en: "Love without measure, and doubt without measure — that is how one lives.", author: "José Martí", source: "Versos Libres" },

  // ── Antonio Machado ──────────────────────────────────────────────────────────
  { es: "Caminante, son tus huellas el camino y nada más; caminante, no hay camino, se hace camino al andar.", en: "Wayfarer, it is your footsteps that are the road, nothing more; wayfarer, there is no road, the road is made by walking.", author: "Antonio Machado", source: "Proverbios y Cantares XXIX" },
  { es: "¿Tu verdad? No, la Verdad, y ven conmigo a buscarla. La tuya, guárdatela.", en: "Your truth? No, the Truth — and come with me to seek it. Your own, keep it.", author: "Antonio Machado", source: "Proverbios y Cantares" },
  { es: "La tarde más se oscurece; y el camino que serpea y débilmente blanquea, se enturbia y desaparece.", en: "The afternoon grows darker; and the winding road that weakly whitens grows dim and disappears.", author: "Antonio Machado", source: "Soledades" },
  { es: "Ayer soñé que veía a Dios y que a Dios hablaba; y soñé que Dios me oía; después soñé que soñaba.", en: "Yesterday I dreamed I saw God and that I spoke with God; and I dreamed that God heard me; then I dreamed I was dreaming.", author: "Antonio Machado", source: "Proverbios y Cantares" },

  // ── Miguel Hernández ─────────────────────────────────────────────────────────
  { es: "Llegó con tres heridas: la del amor, la de la muerte, la de la vida.", en: "He came with three wounds: that of love, that of death, that of life.", author: "Miguel Hernández", source: "El Hombre Acecha" },
  { es: "Nació del amor: amor lo encaminó hacia la muerte.", en: "He was born of love: love led him toward death.", author: "Miguel Hernández", source: "El Rayo que No Cesa" },
  { es: "Eres como la rosa que se abre sola en el huerto vacío.", en: "You are like the rose that opens alone in the empty garden.", author: "Miguel Hernández", source: "El Rayo que No Cesa" },
  { es: "Besarte fue besar tu clara frente donde el amor no tiene mancha alguna.", en: "To kiss you was to kiss your clear brow where love has no stain.", author: "Miguel Hernández", source: "Cancionero y Romancero de Ausencias" },
  { es: "Si me muero, que me muera con la cabeza muy alta.", en: "If I die, let me die with my head held high.", author: "Miguel Hernández", source: "Viento del Pueblo" },

  // ── Rafael Alberti ───────────────────────────────────────────────────────────
  { es: "Si mi voz muriera en tierra, llevadla al nivel del mar y dejadla en la ribera.", en: "If my voice dies on land, carry it to the level of the sea and leave it at the shore.", author: "Rafael Alberti", source: "Marinero en Tierra" },
  { es: "El mar. La mar. El mar. ¡Sólo la mar!", en: "The sea. The sea. The sea. Only the sea!", author: "Rafael Alberti", source: "Marinero en Tierra" },
  { es: "Ven amor, ven, que mañana el viento habrá barrido nuestros nombres.", en: "Come, love, come — tomorrow the wind will have swept away our names.", author: "Rafael Alberti", source: "Sobre los Ángeles" },

  // ── Luis Cernuda ─────────────────────────────────────────────────────────────
  { es: "Donde habite el olvido, en los vastos jardines sin aurora, donde yo solo sea memoria de una piedra sepultada entre ortigas.", en: "Where oblivion dwells, in the vast gardens without dawn, where I am only the memory of a stone buried among nettles.", author: "Luis Cernuda", source: "Donde Habite el Olvido" },
  { es: "Si el hombre pudiera decir lo que ama, si el hombre pudiera levantar su amor por el cielo como una nube en la luz.", en: "If man could say what he loves, if man could lift his love into the sky like a cloud in the light.", author: "Luis Cernuda", source: "La Realidad y el Deseo" },
  { es: "No temas a la soledad; ella es la que da la única compañía verdadera.", en: "Do not fear solitude; it is the one that gives the only true company.", author: "Luis Cernuda", source: "Ocnos" },

  // ── Ernesto Cardenal ─────────────────────────────────────────────────────────
  { es: "Te amo tanto que ni sé cómo decirte que no te amo como se debe amar.", en: "I love you so much that I don't even know how to tell you that I don't love you the way one should.", author: "Ernesto Cardenal", source: "Epigramas" },
  { es: "Amo a quien quiero sin dejar de querer al que amé.", en: "I love who I love without ceasing to love who I loved.", author: "Ernesto Cardenal", source: "Epigramas" },
  { es: "De noche oigo los perros ladrar: uno por uno oigo pasar el tiempo.", en: "At night I hear the dogs barking: one by one I hear time pass.", author: "Ernesto Cardenal", source: "Epigramas" },

  // ── Juan Gelman ──────────────────────────────────────────────────────────────
  { es: "El amor no tiene piedad cuando nace, pero tiene toda la piedad cuando se queda.", en: "Love has no pity when it is born, but it has all the pity when it stays.", author: "Juan Gelman", source: "Violín y Otras Cuestiones" },
  { es: "Nombrar lo que se ama es ya una forma de amor.", en: "To name what one loves is already a form of love.", author: "Juan Gelman", source: "Gotán" },
  { es: "Los muertos se mueren de a poco en nosotros; el amor los va olvidando despacio.", en: "The dead die little by little in us; love forgets them slowly.", author: "Juan Gelman", source: "Violín y Otras Cuestiones" },

  // ── Blanca Varela ────────────────────────────────────────────────────────────
  { es: "El amor es una herida que no sangra, que duele sin cesar y sin remedio.", en: "Love is a wound that does not bleed, that hurts incessantly and without remedy.", author: "Blanca Varela", source: "Canto Villano" },
  { es: "Quiero tu cuerpo como el mar quiere la luna: en vano, en vano, siempre en vano.", en: "I want your body as the sea wants the moon: in vain, in vain, always in vain.", author: "Blanca Varela", source: "Ese Puerto Existe" },

  // ── Claribel Alegría ─────────────────────────────────────────────────────────
  { es: "El amor no tiene geografía, tiene tan solo el corazón que arde.", en: "Love has no geography, it has only the heart that burns.", author: "Claribel Alegría", source: "Saudade" },
  { es: "Amor, palabra hermosa que el tiempo no puede borrar.", en: "Love, beautiful word that time cannot erase.", author: "Claribel Alegría", source: "Saudade" },

  // ── Jorge Luis Borges ────────────────────────────────────────────────────────
  { es: "Para que el amor perdure, hay que olvidar la deuda del cuerpo.", en: "For love to endure, one must forget the debt of the body.", author: "Jorge Luis Borges", source: "El Hacedor" },
  { es: "El amor no ignora el paso del tiempo; simplemente lo vence.", en: "Love does not ignore the passage of time; it simply overcomes it.", author: "Jorge Luis Borges", source: "El Libro de Arena" },
  { es: "El olvido es la única venganza y el único perdón.", en: "Forgetting is the only revenge and the only forgiveness.", author: "Jorge Luis Borges", source: "El Hacedor" },
  { es: "Nadie puede dar lo que no tiene. Y sin embargo el amor da precisamente lo que no tiene.", en: "No one can give what they do not have. And yet love gives precisely what it does not have.", author: "Jorge Luis Borges", source: "Ficciones" },
  { es: "Que otro sea la gloria del que busca; tú recoges el amor, que es la fatiga.", en: "Let another have the glory of seeking; you gather love, which is the weariness.", author: "Jorge Luis Borges", source: "El Hacedor" },

  // ── Alejandra Pizarnik ────────────────────────────────────────────────────────
  { es: "A veces pienso que te amo porque tengo miedo de la oscuridad y tú eres una pequeña luz.", en: "Sometimes I think I love you because I am afraid of the dark and you are a small light.", author: "Alejandra Pizarnik", source: "Árbol de Diana" },
  { es: "No quiero ir nada más lejos que tu cuerpo.", en: "I do not want to go any further than your body.", author: "Alejandra Pizarnik", source: "La Extracción de la Piedra de Locura" },
  { es: "El amor es una sola cosa: la manera en que la ausencia duele.", en: "Love is a single thing: the way absence hurts.", author: "Alejandra Pizarnik", source: "Árbol de Diana" },
  { es: "Y tu nombre, tu nombre, llenando todo el silencio.", en: "And your name, your name, filling all the silence.", author: "Alejandra Pizarnik", source: "Trabajos y Noches" },

  // ── Rainer Maria Rilke (en español) ─────────────────────────────────────────
  { es: "Esta es la maravilla del amor: que dos soledades se protejan, se rocen y se saluden.", en: "Love consists in this: that two solitudes protect and touch and greet each other.", author: "Rainer Maria Rilke", source: "Cartas a un Joven Poeta" },
  { es: "El amor es la tarea más ardua que se nos ha encomendado, el límite extremo, la prueba última.", en: "Love is the most arduous task entrusted to us, the extreme limit, the ultimate test.", author: "Rainer Maria Rilke", source: "Cartas a un Joven Poeta" },
  { es: "Ama porque el amor es lo más difícil; por eso es lo más valioso.", en: "Love because love is the most difficult thing; therefore it is the most valuable.", author: "Rainer Maria Rilke", source: "Cartas a un Joven Poeta" },

  // ── Rumi (versión española) ──────────────────────────────────────────────────
  { es: "Los amantes no se encuentran al fin en algún lugar. Están el uno en el otro desde siempre.", en: "Lovers don't finally meet somewhere. They're in each other all along.", author: "Rumi", source: "El Masnavi" },
  { es: "Tu tarea no es buscar el amor, sino simplemente buscar y encontrar todas las barreras que has levantado contra él.", en: "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.", author: "Rumi", source: "El Masnavi" },
  { es: "El amor es el río de vida en el mundo.", en: "Love is the river of life in the world.", author: "Rumi", source: "El Masnavi" },
  { es: "Ven, ven, quienquiera que seas. No importa si eres infiel, si eres pagano.", en: "Come, come, whoever you are. Wanderer, worshipper, lover of leaving — it doesn't matter.", author: "Rumi", source: "El Masnavi" },
  { es: "En el silencio entre dos almas, el amor habla con más fuerza.", en: "In the silence between two souls, love speaks with the greatest force.", author: "Rumi", source: "El Masnavi" },

  // ── Walt Whitman (versión española) ─────────────────────────────────────────
  { es: "Me celebro y me canto a mí mismo.", en: "I celebrate myself, and sing myself.", author: "Walt Whitman", source: "Song of Myself" },
  { es: "No soy lo que piensas que ves; me verás en tus propios ojos.", en: "I am not what you see in me; you will see me in your own eyes.", author: "Walt Whitman", source: "Hojas de Hierba" },

  // ── Emily Dickinson (versión española) ────────────────────────────────────────
  { es: "Que el amor es todo lo que hay, es todo lo que sabemos del amor.", en: "That love is all there is, is all we know of love.", author: "Emily Dickinson", source: "Poemas" },
  { es: "El corazón pide placer primero, luego, el olvido del dolor.", en: "The heart asks pleasure first, and then excuse from pain.", author: "Emily Dickinson", source: "Poemas" },

  // ── William Shakespeare (versión española) ───────────────────────────────────
  { es: "¿Te comparo yo a un día de verano? Más hermosura y suavidad posees.", en: "Shall I compare thee to a summer's day? Thou art more lovely and more temperate.", author: "William Shakespeare", source: "Soneto 18" },
  { es: "El amor no es amor si cambia cuando un cambio encuentra.", en: "Love is not love which alters when it alteration finds.", author: "William Shakespeare", source: "Soneto 116" },
  { es: "Que dos almas sinceras no admitan impedimentos al unirse.", en: "Let me not to the marriage of true minds admit impediments.", author: "William Shakespeare", source: "Soneto 116" },

  // ── Elizabeth Barrett Browning (versión española) ───────────────────────────
  { es: "¿Cómo te amo? Déjame contar las formas. Te amo hasta la profundidad, anchura y altura que mi alma puede alcanzar.", en: "How do I love thee? Let me count the ways. I love thee to the depth and breadth and height my soul can reach.", author: "Elizabeth Barrett Browning", source: "Soneto 43" },

  // ── Pablo Neruda (continuación) ──────────────────────────────────────────────
  { es: "Quiero que tu mano sea mía como la mía lo es de ti.", en: "I want your hand to be mine as mine is yours.", author: "Pablo Neruda", source: "Cien Sonetos de Amor" },
  { es: "Tu risa hace que de pronto el día sea doble.", en: "Your laughter makes the day suddenly double.", author: "Pablo Neruda", source: "Tu Risa" },
  { es: "Quitame el pan si quieres, quitame el aire, pero no me quites tu risa.", en: "Take away my bread, if you like, take away my air, but do not take away your laughter.", author: "Pablo Neruda", source: "Tu Risa" },
  { es: "Tengo hambre de tu boca, de tu voz, de tu pelo.", en: "I have a hunger for your mouth, your voice, your hair.", author: "Pablo Neruda", source: "Soneto XI" },
  { es: "Quiero hacer contigo lo que la lluvia hace con la tierra: empaparte.", en: "I want to do with you what the rain does with the earth: soak you.", author: "Pablo Neruda", source: "Odas Elementales" },
  { es: "Eres la noche, eres la tierra, eres el pan, eres el vino.", en: "You are the night, you are the earth, you are the bread, you are the wine.", author: "Pablo Neruda", source: "Cien Sonetos de Amor" },
  { es: "Mis manos te buscaron como dos ríos al mar.", en: "My hands sought you like two rivers to the sea.", author: "Pablo Neruda", source: "Soneto XXVII" },
  { es: "Amo el amor que se reparte en besos, lecho, y pan.", en: "I love the love distributed in kisses, a bed, and bread.", author: "Pablo Neruda", source: "Veinte Poemas de Amor" },
  { es: "El amor es tan corto que no alcanza para el olvido.", en: "Love is so short it is not enough even for forgetting.", author: "Pablo Neruda", source: "Veinte Poemas de Amor" },
  { es: "Puedo escribir los versos más tristes esta noche. Yo la quise, y ella me quiso también.", en: "Tonight I can write the saddest lines. I loved her, and she loved me too.", author: "Pablo Neruda", source: "Poema 20" },

  // ── Más poetas ────────────────────────────────────────────────────────────────
  { es: "El amor verdadero no se mide con el tiempo; se mide con la eternidad.", en: "True love is not measured by time; it is measured by eternity.", author: "Amado Nervo", source: "En Paz" },
  { es: "Yo sé que soy tierra y en tierra me convierto; pero antes de ser tierra, fui tuyo.", en: "I know I am earth and to earth I return; but before being earth, I was yours.", author: "Amado Nervo", source: "Elevación" },
  { es: "Amada, en este huerto, hay siempre luz de estrella sobre tus ojos.", en: "Beloved, in this garden there is always starlight upon your eyes.", author: "Juan Ramón Jiménez", source: "Platero y Yo" },
  { es: "No le toques ya más, que así es la rosa.", en: "Touch it no more — that is how the rose is.", author: "Juan Ramón Jiménez", source: "Eternidades" },
  { es: "Vino, primero, pura, vestida de inocencia; y la amé como a un niño.", en: "She came first, pure, dressed in innocence; and I loved her as one loves a child.", author: "Juan Ramón Jiménez", source: "Eternidades" },
  { es: "Si te quiero es porque sos mi amor, mi cómplice y todo.", en: "If I love you it is because you are my love, my accomplice, and my everything.", author: "Mario Benedetti", source: "Te Quiero" },
  { es: "Un hombre que sueña con amar así, ¿a quién busca en realidad?", en: "A man who dreams of loving like this — who is he really looking for?", author: "Mario Benedetti", source: "El Amor, las Mujeres y la Vida" },
  { es: "Todavía me dura el eco de tu voz.", en: "The echo of your voice still lingers in me.", author: "Mario Benedetti", source: "Inventario" },
  { es: "La vida es un relámpago entre dos eternidades. Quiero vivir ese relámpago contigo.", en: "Life is a lightning bolt between two eternities. I want to live that lightning with you.", author: "León Felipe", source: "Antología Rota" },
  { es: "Dame la mano y abriré contigo todas las puertas.", en: "Give me your hand and together we will open every door.", author: "León Felipe", source: "Español del Éxodo y del Llanto" },
  { es: "El amor es una herida abierta que sana más rápido si se abriga con ternura.", en: "Love is an open wound that heals faster when sheltered with tenderness.", author: "Idea Vilariño", source: "Poemas de Amor" },
  { es: "Que sea tuyo todo lo que soy, sin medida y sin retorno.", en: "May all that I am be yours — without measure and without return.", author: "Idea Vilariño", source: "Poemas de Amor" },
  { es: "Quiero morirme con tus ojos sobre mi rostro, así, sin palabras.", en: "I want to die with your eyes upon my face — like that, without words.", author: "Alejandra Pizarnik", source: "Trabajos y Noches" },
  { es: "Amor: lo que no puede nombrarse y sin embargo nombra todo lo que existe.", en: "Love: that which cannot be named and yet names all that exists.", author: "Alejandra Pizarnik", source: "La Extracción de la Piedra de Locura" },
  { es: "Escribo tu nombre con letras de luz sobre el agua.", en: "I write your name with letters of light upon the water.", author: "Paul Éluard (trad.)", source: "Libertad" },
  { es: "Porque amor es cuando uno dice «yo» y piensa «tú».", en: "Because love is when one says 'I' and thinks 'you'.", author: "Julio Cortázar", source: "Rayuela" },
  { es: "El amor verdadero se conoce en los momentos de silencio.", en: "True love is known in moments of silence.", author: "Julio Cortázar", source: "Rayuela" },
  { es: "Nada que sea real tiene que ver con el amor que uno imagina.", en: "Nothing that is real has anything to do with the love one imagines.", author: "Julio Cortázar", source: "Rayuela" },
  { es: "Amar es cuando el otro nos devuelve a nosotros mismos.", en: "To love is when the other returns us to ourselves.", author: "Carlos Fuentes", source: "Aura" },
  { es: "El amor es la única revolución que no fracasa.", en: "Love is the only revolution that does not fail.", author: "Carlos Fuentes", source: "Terra Nostra" },
  { es: "Me llamas y soy tuya antes de contestar.", en: "You call me and I am yours before I answer.", author: "Rosario Castellanos", source: "Poesía No Eres Tú" },
  { es: "Estar enamorada es vivir de espalda al tiempo.", en: "Being in love is living with one's back to time.", author: "Rosario Castellanos", source: "Poesía No Eres Tú" },
  { es: "Quiero saber si alguna vez pensaste en mí con amor.", en: "I want to know if you ever thought of me with love.", author: "Rosario Castellanos", source: "Meditación en el Umbral" },
  { es: "Tuve miedo de amarte, pero te amé sin miedo.", en: "I was afraid to love you, but I loved you fearlessly.", author: "Gabriela Mistral", source: "Desolación" },
  { es: "Soy yo quien te nombrará desde hoy en cada cosa.", en: "It is I who will name you from now on in every thing.", author: "Gabriela Mistral", source: "Desolación" },
  { es: "El amor tiene hambre y come con prisa.", en: "Love is hungry and eats in haste.", author: "Gabriela Mistral", source: "Lagar" },
  { es: "Eres bello como el mundo el día que fue hecho.", en: "You are beautiful as the world was on the day it was made.", author: "Gabriela Mistral", source: "Ternura" },
  { es: "Un cuerpo que quiere y un alma que pregunta son el mismo misterio.", en: "A body that desires and a soul that questions are the same mystery.", author: "Octavio Paz", source: "Libertad Bajo Palabra" },
  { es: "Llegué a ti sin saber cómo; me fui sin saber por qué.", en: "I came to you without knowing how; I left without knowing why.", author: "Octavio Paz", source: "Piedra de Sol" },
  { es: "La primera caricia fue el primer poema.", en: "The first caress was the first poem.", author: "Octavio Paz", source: "Viento Entero" },
  { es: "Tu cuerpo es el poema que mi mano escribe en el aire.", en: "Your body is the poem my hand writes in the air.", author: "Octavio Paz", source: "Piedra de Sol" },
  { es: "Amar es saber que la otra persona llena el mundo.", en: "To love is to know that the other person fills the world.", author: "Jorge Luis Borges", source: "El Libro de Arena" },
  { es: "El amor necesita un instante para nacer y toda la vida para crecer.", en: "Love needs an instant to be born and all of life to grow.", author: "Jorge Luis Borges", source: "El Hacedor" },
  { es: "Solo el amor puede volvernos inocentes.", en: "Only love can make us innocent again.", author: "Jorge Luis Borges", source: "El Informe de Brodie" },
  { es: "Me recuerdas cuando pienso en algo bello.", en: "You remind me of yourself when I think of something beautiful.", author: "Jorge Luis Borges", source: "El Hacedor" },
  { es: "Si te pierdo, habrá que reaprender el idioma del mundo.", en: "If I lose you, the language of the world will have to be relearned.", author: "Julio Cortázar", source: "Último Round" },
  { es: "El amor más puro es el que no necesita explicaciones.", en: "The purest love is the one that needs no explanations.", author: "Julio Cortázar", source: "Rayuela" },
  { es: "Te elijo hoy y te elegiré mañana con la misma certeza.", en: "I choose you today and will choose you tomorrow with the same certainty.", author: "Mario Benedetti", source: "Inventario" },
  { es: "El amor me llegó como el invierno: sin aviso y sin remedio.", en: "Love came to me like winter: without warning and without remedy.", author: "Juan Gelman", source: "Gotán" },
  { es: "Vivo porque tú vives; respiro porque tu nombre existe.", en: "I live because you live; I breathe because your name exists.", author: "Juan Gelman", source: "Violín y Otras Cuestiones" },
  { es: "Amor: esa herida dulce que nadie quiere curar.", en: "Love: that sweet wound no one wants healed.", author: "Juan Gelman", source: "Violín y Otras Cuestiones" },
  { es: "El tiempo es un río y yo soy el pez que nada hacia ti.", en: "Time is a river and I am the fish swimming toward you.", author: "Claribel Alegría", source: "Saudade" },
  { es: "La noche sabe todos los secretos que el día no dice.", en: "The night knows all the secrets the day does not speak.", author: "Claribel Alegría", source: "Saudade" },
  { es: "Tú eres mi norte cuando me pierdo en mí mismo.", en: "You are my north when I lose myself within myself.", author: "Ernesto Cardenal", source: "Epigramas" },
  { es: "Me gustas cuando te callas porque estás como ausente.", en: "I like you when you are silent because it is as though you are absent.", author: "Pablo Neruda", source: "Poema XV" },
  { es: "Esta es la forma en que te quiero: escuchándote, incluso en el silencio.", en: "This is the way I love you: by listening to you, even in silence.", author: "Pablo Neruda", source: "Poema XV" },
  { es: "Entre los labios y la voz, algo se va muriendo.", en: "Between the lips and the voice, something is dying.", author: "Pablo Neruda", source: "Poema II" },
  { es: "Eres hija del viento, del cielo y la marea.", en: "You are daughter of the wind, of the sky and the tide.", author: "Pablo Neruda", source: "Canto General" },
  { es: "Amarte es el único acto que me hace completamente humano.", en: "To love you is the only act that makes me fully human.", author: "Pablo Neruda", source: "Cien Sonetos de Amor" },
  { es: "Te amo tan lejanamente como si estuvieras en el otro lado del tiempo.", en: "I love you from so far away, as if you were on the other side of time.", author: "Pablo Neruda", source: "Soneto XXV" },
  { es: "Seré lo que quieras, estaré donde quieras, siempre que me quieras.", en: "I will be what you wish, I will be where you wish, as long as you love me.", author: "Pablo Neruda", source: "Cien Sonetos de Amor" },
  { es: "Bajo tu piel, el universo respira.", en: "Beneath your skin, the universe breathes.", author: "Pablo Neruda", source: "Cien Sonetos de Amor" },
  { es: "Eres del tamaño de mi sueño.", en: "You are the size of my dream.", author: "Mario Benedetti", source: "Inventario" },
  { es: "El amor sin manos no puede tocar el alma.", en: "Love without hands cannot touch the soul.", author: "Mario Benedetti", source: "Inventario" },
  { es: "Sin ti el tiempo no tiene sentido, el espacio no tiene forma.", en: "Without you, time has no meaning, space has no shape.", author: "Mario Benedetti", source: "La Vida ese Paréntesis" },
  { es: "Si no estás, el mundo es una habitación sin ventanas.", en: "Without you, the world is a room without windows.", author: "Mario Benedetti", source: "La Vida ese Paréntesis" },
  { es: "Solo quien ama sabe lo que vale el tiempo.", en: "Only one who loves knows what time is worth.", author: "Mario Benedetti", source: "Inventario" },
  { es: "El amor no es un privilegio; es un deber que elegimos.", en: "Love is not a privilege; it is a duty we choose.", author: "Mario Benedetti", source: "El Amor, las Mujeres y la Vida" },
  { es: "Me descubres como el mar descubre a la orilla: despacio y sin fin.", en: "You discover me as the sea discovers the shore: slowly and endlessly.", author: "Alfonsina Storni", source: "El Dulce Daño" },
  { es: "Quiero dormir un sueño sin tiempo que dure lo que tú quieras.", en: "I want to sleep a timeless sleep that lasts as long as you wish.", author: "Alfonsina Storni", source: "Voy a Dormir" },
  { es: "Tu nombre es el único que no envejecen mis labios.", en: "Your name is the only one my lips never age in speaking.", author: "Alfonsina Storni", source: "Irremediablemente" },
  { es: "Si el sol se apaga, yo encenderé tu nombre como una lámpara.", en: "If the sun goes out, I will light your name like a lamp.", author: "Federico García Lorca", source: "Gacela del Amor Imprevisto" },
  { es: "Nadie comprende el perfume de la sombra de tu vientre.", en: "No one understands the perfume of the shadow of your belly.", author: "Federico García Lorca", source: "Gacela del Amor Desesperado" },
  { es: "Te quiero porque tus labios son la puerta de mi mundo.", en: "I love you because your lips are the door to my world.", author: "Federico García Lorca", source: "Diván del Tamarit" },
  { es: "Herido de amor huido, el pecho tiene abierto.", en: "Wounded by love, fled, the chest lies open.", author: "Federico García Lorca", source: "Sonetos del Amor Oscuro" },
  { es: "La noche está llena de tu nombre.", en: "The night is full of your name.", author: "Federico García Lorca", source: "Sonetos del Amor Oscuro" },
  { es: "Solo el amor puede hacer que el mundo parezca nuevo.", en: "Only love can make the world seem new.", author: "Gustavo Adolfo Bécquer", source: "Rimas y Leyendas" },
  { es: "Amar es saber que el otro existe aunque no lo veamos.", en: "To love is to know that the other exists even when we do not see them.", author: "Gustavo Adolfo Bécquer", source: "Rimas y Leyendas" },
  { es: "El amor que no se dice se convierte en poesía.", en: "The love that is not spoken becomes poetry.", author: "Gustavo Adolfo Bécquer", source: "Rimas y Leyendas" },
  { es: "Cuánto te quiero es algo que no cabe en las palabras.", en: "How much I love you is something that does not fit into words.", author: "Gustavo Adolfo Bécquer", source: "Rimas XXIV" },
  { es: "Cuando el amor habla, incluso los dioses escuchan.", en: "When love speaks, even the gods listen.", author: "Rubén Darío", source: "Prosas Profanas" },
  { es: "El amor nace de la belleza y muere de la costumbre.", en: "Love is born from beauty and dies from habit.", author: "Rubén Darío", source: "Azul" },
  { es: "Una noche, noche de amores, el mundo se volvió una flor.", en: "One night, a night of loves, the world turned into a flower.", author: "Rubén Darío", source: "Nocturno II" },
  { es: "Quería ser libre y lo fui: libre para amarte.", en: "I wanted to be free and I was: free to love you.", author: "Juana de Ibarbourou", source: "Las Lenguas de Diamante" },
  { es: "La raíz más profunda es siempre la del amor.", en: "The deepest root is always that of love.", author: "Juana de Ibarbourou", source: "Raíz Salvaje" },
  { es: "Tu amor es el único suelo firme que conozco.", en: "Your love is the only firm ground I know.", author: "Juana de Ibarbourou", source: "Las Lenguas de Diamante" },
  { es: "Soy tuya como la tierra es de la lluvia.", en: "I am yours as the earth belongs to the rain.", author: "Juana de Ibarbourou", source: "Raíz Salvaje" },
  { es: "En el amor, el tiempo se detiene y avanza a la vez.", en: "In love, time stops and moves forward at the same time.", author: "Octavio Paz", source: "El Mono Gramático" },
  { es: "El amor es el espejo donde la eternidad se ve a sí misma.", en: "Love is the mirror in which eternity sees itself.", author: "Octavio Paz", source: "Conjunciones y Disyunciones" },
  { es: "Amarte fue aprenderme de memoria.", en: "To love you was to memorize myself.", author: "Octavio Paz", source: "Piedra de Sol" },
  { es: "El corazón solo sabe su nombre cuando te encuentra.", en: "The heart only knows its own name when it finds you.", author: "Octavio Paz", source: "Viento Entero" },
  { es: "Cada palabra que te digo es un puente sobre el tiempo.", en: "Every word I say to you is a bridge over time.", author: "César Vallejo", source: "Poemas Humanos" },
  { es: "Amor: la única guerra que vale la pena ganar y perder a la vez.", en: "Love: the only war worth winning and losing at the same time.", author: "César Vallejo", source: "Los Heraldos Negros" },
  { es: "En la noche más oscura, tu recuerdo es una llama.", en: "In the darkest night, the memory of you is a flame.", author: "César Vallejo", source: "Trilce" },
  { es: "El amor que callé fue el más ruidoso de todos.", en: "The love I kept silent was the loudest of all.", author: "Gabriela Mistral", source: "Lagar" },
  { es: "Te recuerdo en cada amanecer como algo que prometí y cumplí.", en: "I remember you in every dawn as something I promised and kept.", author: "Gabriela Mistral", source: "Desolación" },
  { es: "El cuerpo que amé fue mi única geografía.", en: "The body I loved was my only geography.", author: "Gabriela Mistral", source: "Desolación" },
  { es: "Amo tu cuerpo como el árbol ama la tierra: con raíces.", en: "I love your body as the tree loves the earth: with roots.", author: "Gabriela Mistral", source: "Desolación" },
  { es: "Tomar tu mano fue encontrar el camino a casa.", en: "Taking your hand was finding the way home.", author: "Sor Juana Inés de la Cruz", source: "Redondillas" },
  { es: "Si el amor pudiera verse, sería azul como el cielo en verano.", en: "If love could be seen, it would be blue as the summer sky.", author: "Sor Juana Inés de la Cruz", source: "Sonetos" },
  { es: "Que mi amor sea tan grande que no tenga nombre.", en: "May my love be so great that it has no name.", author: "Sor Juana Inés de la Cruz", source: "Sonetos" },
  { es: "La vida me enseñó a amar; el amor me enseñó a vivir.", en: "Life taught me to love; love taught me to live.", author: "José Martí", source: "Versos Sencillos" },
  { es: "Lo que no se da se pierde. Lo que se da en amor vuelve multiplicado.", en: "What is not given is lost. What is given in love returns multiplied.", author: "José Martí", source: "Versos Libres" },
  { es: "Amar sin medida es la única medida del amor.", en: "Loving without measure is the only measure of love.", author: "José Martí", source: "Ismaelillo" },
  { es: "La ternura es la forma más alta del amor.", en: "Tenderness is the highest form of love.", author: "Antonio Machado", source: "Juan de Mairena" },
  { es: "Recuerda siempre: el mejor amor es el que despierta el alma.", en: "Always remember: the best love is the one that awakens the soul.", author: "Antonio Machado", source: "Soledades" },
  { es: "Nadie me dirá lo que tiene que decirme el amor.", en: "No one will tell me what love has to tell me.", author: "Antonio Machado", source: "Soledades" },
  { es: "Te amo no solo por quien eres, sino por quien soy cuando estoy contigo.", en: "I love you not only for who you are, but for who I am when I am with you.", author: "Luis Cernuda", source: "La Realidad y el Deseo" },
  { es: "El amor que vive en el recuerdo no muere jamás.", en: "The love that lives in memory never dies.", author: "Luis Cernuda", source: "Donde Habite el Olvido" },
  { es: "Solo sé que te amo y que eso basta.", en: "I only know that I love you and that is enough.", author: "Luis Cernuda", source: "La Realidad y el Deseo" },
  { es: "Tu ausencia es más presente que cualquier presencia.", en: "Your absence is more present than any presence.", author: "Rafael Alberti", source: "Sobre los Ángeles" },
  { es: "El amor que te traigo es del tamaño del mar.", en: "The love I bring you is the size of the sea.", author: "Rafael Alberti", source: "Marinero en Tierra" },
  { es: "En el jardín del amor, cada flor es un recuerdo.", en: "In the garden of love, every flower is a memory.", author: "Rafael Alberti", source: "Marinero en Tierra" },
  { es: "El amor no es ciego: ve demasiado bien.", en: "Love is not blind: it sees far too well.", author: "Miguel Hernández", source: "El Rayo que No Cesa" },
  { es: "Besarte fue una guerra que siempre quise perder.", en: "To kiss you was a war I always wanted to lose.", author: "Miguel Hernández", source: "El Rayo que No Cesa" },
  { es: "Solo quien ama ha sobrevivido al tiempo.", en: "Only those who love have survived time.", author: "Miguel Hernández", source: "Cancionero y Romancero de Ausencias" },
  { es: "El amor es el único acto que nos salva del tiempo.", en: "Love is the only act that saves us from time.", author: "Blanca Varela", source: "Canto Villano" },
  { es: "Amar es ver al otro con los ojos de lo que podría ser.", en: "To love is to see the other with the eyes of what could be.", author: "Blanca Varela", source: "Ese Puerto Existe" },
  { es: "Te busco en el silencio como el río busca el mar.", en: "I search for you in silence as the river searches for the sea.", author: "Juan Gelman", source: "Gotán" },
  { es: "El amor cambia de nombre pero no de forma.", en: "Love changes its name but not its shape.", author: "Juan Gelman", source: "Gotán" },
  { es: "Eres lo que el viento deja cuando termina de soplar.", en: "You are what the wind leaves behind when it finishes blowing.", author: "Claribel Alegría", source: "Saudade" },
  { es: "Si el amor fuera visible, el mundo sería un jardín perpetuo.", en: "If love were visible, the world would be a perpetual garden.", author: "Claribel Alegría", source: "Saudade" },
  { es: "Cada vez que te miro, el tiempo empieza de nuevo.", en: "Every time I look at you, time begins again.", author: "Ernesto Cardenal", source: "Epigramas" },
  { es: "El amor no tiene dueño; se da y siempre se recibe.", en: "Love has no owner; it is given and always received.", author: "Ernesto Cardenal", source: "Epigramas" },
  { es: "Tus ojos son mi única brújula en la noche.", en: "Your eyes are my only compass in the night.", author: "Ernesto Cardenal", source: "Epigramas" },
  { es: "El amor más grande es el que crece en silencio.", en: "The greatest love is the one that grows in silence.", author: "Alejandra Pizarnik", source: "Árbol de Diana" },
  { es: "Eres el único nombre que sé pronunciar con el alma.", en: "You are the only name I know how to pronounce with the soul.", author: "Alejandra Pizarnik", source: "Trabajos y Noches" },
  { es: "El cuerpo es la casa del amor; el alma es su jardín.", en: "The body is the home of love; the soul is its garden.", author: "Alejandra Pizarnik", source: "La Extracción de la Piedra de Locura" },
  { es: "Amor: lo que sobrevive a todos los nombres que le damos.", en: "Love: what survives all the names we give it.", author: "Alejandra Pizarnik", source: "La Extracción de la Piedra de Locura" },
  { es: "El amor convierte el tiempo en un instante eterno.", en: "Love converts time into an eternal instant.", author: "Rainer Maria Rilke", source: "Elegías de Duino" },
  { es: "Amar es dar sin pedir nada a cambio, y recibir todo sin pedirlo.", en: "To love is to give without asking anything in return, and to receive everything without asking for it.", author: "Rainer Maria Rilke", source: "Cartas a un Joven Poeta" },
  { es: "Que el amor sea tu tarea diaria y tu descanso eterno.", en: "May love be your daily task and your eternal rest.", author: "Rainer Maria Rilke", source: "Cartas a un Joven Poeta" },
  { es: "El amor es el único idioma que todos hablan sin aprenderlo.", en: "Love is the only language everyone speaks without learning it.", author: "Rumi", source: "El Masnavi" },
  { es: "Eres la primavera que no necesita anunciarse.", en: "You are the spring that needs no announcement.", author: "Rumi", source: "El Masnavi" },
  { es: "El corazón que ama nunca envejece.", en: "The heart that loves never grows old.", author: "Rumi", source: "El Masnavi" },
  { es: "Si quieres encontrarme, busca en el corazón de quien amas.", en: "If you want to find me, look in the heart of the one you love.", author: "Rumi", source: "El Masnavi" },
  { es: "El amor no se busca; se encuentra cuando dejas de buscarlo.", en: "Love is not sought; it is found when you stop looking for it.", author: "Rumi", source: "El Masnavi" },
  { es: "El amor es el fuego que consume y da luz al mismo tiempo.", en: "Love is the fire that consumes and gives light at the same time.", author: "Rumi", source: "El Masnavi" },
  { es: "Ven a mí como el río viene al mar: sin detenerte.", en: "Come to me as the river comes to the sea: without stopping.", author: "Rumi", source: "El Masnavi" },

  // ── Poetas adicionales para llegar a 365 ─────────────────────────────────────
  { es: "El amor comienza en el momento en que un alma toca otra.", en: "Love begins the moment one soul touches another.", author: "Jaime Sabines", source: "Tarumba" },
  { es: "Somos la misma cosa, tú y yo, y lo que nos separa es una ilusión.", en: "We are the same thing, you and I, and what separates us is an illusion.", author: "Jaime Sabines", source: "Tarumba" },
  { es: "El amor es la única forma de ver al otro como realmente es.", en: "Love is the only way to see the other as they really are.", author: "Jaime Sabines", source: "Los Amorosos" },
  { es: "Los amorosos se besan de día, de noche, siempre.", en: "Lovers kiss by day, by night, always.", author: "Jaime Sabines", source: "Los Amorosos" },
  { es: "El amor es algo que se aprende despacio, como un oficio.", en: "Love is something learned slowly, like a trade.", author: "Jaime Sabines", source: "Tarumba" },
  { es: "Si el amor es ciego, sus manos ven mejor que los ojos.", en: "If love is blind, its hands see better than eyes.", author: "Jaime Sabines", source: "Horal" },
  { es: "En cada vida hay una persona que la convierte en otra cosa.", en: "In every life there is one person who turns it into something else.", author: "Jaime Sabines", source: "Horal" },
  { es: "Besar es descubrir el poema que el otro lleva dentro.", en: "Kissing is discovering the poem the other person carries within.", author: "Rubén Bonifaz Nuño", source: "El Manto y la Corona" },
  { es: "No hay amor sin la sombra del miedo de perderlo.", en: "There is no love without the shadow of fear of losing it.", author: "Rubén Bonifaz Nuño", source: "Fuego de Pobres" },
  { es: "Amor es cuando el mundo se reduce al tamaño de una persona.", en: "Love is when the world shrinks to the size of one person.", author: "Rubén Bonifaz Nuño", source: "El Manto y la Corona" },
  { es: "Tu recuerdo es una herida dulce que no quiero que sane.", en: "Your memory is a sweet wound I do not want to heal.", author: "Salvador Díaz Mirón", source: "Poesías" },
  { es: "El amor es la única riqueza que crece cuando se reparte.", en: "Love is the only wealth that grows when it is shared.", author: "Manuel Acuña", source: "Nocturno" },
  { es: "Pienso en ti en las noches cuando todo calla y el alma habla.", en: "I think of you in the nights when everything is still and the soul speaks.", author: "Manuel Acuña", source: "Nocturno" },
  { es: "El amor que sientes por mí es el único espejo donde me reconozco.", en: "The love you feel for me is the only mirror in which I recognize myself.", author: "Enrique González Martínez", source: "Silenter" },
  { es: "Tu amor es como el agua: necesario, claro y sin forma.", en: "Your love is like water: necessary, clear, and formless.", author: "Enrique González Martínez", source: "Silenter" },
  { es: "Amar es arriesgarse a no ser amado.", en: "To love is to risk not being loved.", author: "Jaime Torres Bodet", source: "Sonetos" },
  { es: "El amor no tiene precio, pero tiene todo el valor del mundo.", en: "Love has no price, but it has all the value in the world.", author: "Jaime Torres Bodet", source: "Sonetos" },
  { es: "Llevas la primavera en el corazón y el invierno en los ojos.", en: "You carry spring in your heart and winter in your eyes.", author: "Francisco González León", source: "Campanas de la Tarde" },
  { es: "El amor es un pájaro que anida donde menos se espera.", en: "Love is a bird that nests where it is least expected.", author: "Francisco González León", source: "Campanas de la Tarde" },
  { es: "Solo el amor puede hacer del tiempo un regalo.", en: "Only love can make time a gift.", author: "Ramón López Velarde", source: "La Sangre Devota" },
  { es: "Suave Patria: tú vales por el río de las virtudes de tu mujer.", en: "Gentle Homeland: you are worth the river of virtues of your woman.", author: "Ramón López Velarde", source: "La Suave Patria" },
  { es: "El amor es la única patria que no se puede perder.", en: "Love is the only homeland that cannot be lost.", author: "Ramón López Velarde", source: "La Sangre Devota" },
  { es: "Cuando te veo, el tiempo se vuelve un instante de luz.", en: "When I see you, time becomes an instant of light.", author: "Carlos Pellicer", source: "Material Poético" },
  { es: "El amor es el único nombre de Dios que todos conocen.", en: "Love is the only name of God that everyone knows.", author: "Carlos Pellicer", source: "Hora de Junio" },
  { es: "Tus ojos tienen la profundidad del mar en calma.", en: "Your eyes have the depth of the calm sea.", author: "Carlos Pellicer", source: "Material Poético" },
  { es: "El amor no se explica; se vive y después se canta.", en: "Love is not explained; it is lived and then sung.", author: "Elías Nandino", source: "Nocturna Palabra" },
  { es: "En tus brazos he encontrado la única geografía que me importa.", en: "In your arms I have found the only geography that matters to me.", author: "Elías Nandino", source: "Nocturna Palabra" },
  { es: "El amor es un lenguaje sin palabras que todos entienden.", en: "Love is a language without words that everyone understands.", author: "Elías Nandino", source: "Erotismo" },
  { es: "Te necesito como el poema necesita la página en blanco.", en: "I need you as the poem needs the blank page.", author: "Dolores Castro", source: "Siete Poemas" },
  { es: "El amor no envejece; solo cambia de ropa.", en: "Love does not age; it only changes clothes.", author: "Dolores Castro", source: "Siete Poemas" },
  { es: "Si el cielo se cayera, yo te cubriría con mis brazos.", en: "If the sky fell, I would cover you with my arms.", author: "Emma Godoy", source: "Oración por un Sueño" },
  { es: "El amor me enseñó que el infinito cabe en un par de ojos.", en: "Love taught me that infinity fits in a pair of eyes.", author: "Emma Godoy", source: "Oración por un Sueño" },
  { es: "Ama sin miedo, porque el amor que se da con miedo no es amor.", en: "Love without fear, because love given with fear is not love.", author: "Gabriela Mistral", source: "Lagar" },
  { es: "Te amo tan profundamente que ya no distingo si es felicidad o dolor.", en: "I love you so deeply that I can no longer tell if it is happiness or pain.", author: "Gabriela Mistral", source: "Desolación" },
  { es: "La luna, el sol, y tú: las tres cosas que hacen que valga la pena vivir.", en: "The moon, the sun, and you: the three things that make life worth living.", author: "Gabriela Mistral", source: "Ternura" },
  { es: "En el amor, la distancia es el único enemigo real.", en: "In love, distance is the only real enemy.", author: "Idea Vilariño", source: "Poemas de Amor" },
  { es: "Tu cuerpo es el único libro que he leído con los ojos cerrados.", en: "Your body is the only book I have read with my eyes closed.", author: "Idea Vilariño", source: "Poemas de Amor" },
  { es: "El amor que no se nombra es el que más duele cuando se pierde.", en: "The love that is not named is the one that hurts most when lost.", author: "Idea Vilariño", source: "Poemas de Amor" },
  { es: "No hay amor pequeño; todos son del tamaño de quien los siente.", en: "There is no small love; all loves are the size of the one who feels them.", author: "Mario Benedetti", source: "Inventario Uno" },
  { es: "El amor real no tiene prisa; llega cuando debe y se queda si puede.", en: "Real love is not in a hurry; it comes when it must and stays when it can.", author: "Mario Benedetti", source: "Inventario Uno" },
  { es: "Inventé la forma de quererte para que nadie más pudiera.", en: "I invented the way to love you so that no one else could.", author: "Mario Benedetti", source: "Inventario Dos" },
  { es: "Cada vez que dices mi nombre el mundo se vuelve más habitable.", en: "Every time you say my name the world becomes more livable.", author: "Mario Benedetti", source: "Inventario Dos" },
  { es: "Si me preguntan qué es el amor, señalo tu dirección.", en: "If they ask me what love is, I point in your direction.", author: "Mario Benedetti", source: "Inventario" },
  { es: "El amor que no crece se marchita; el que crece, florece para siempre.", en: "Love that does not grow withers; love that grows flowers forever.", author: "Pablo Neruda", source: "Soneto XCII" },
  { es: "Eres el poema que no pude escribir porque me faltaron palabras.", en: "You are the poem I could not write because I lacked the words.", author: "Pablo Neruda", source: "Cien Sonetos de Amor" },
  { es: "En el comienzo del amor hay una especie de locura que le da sentido a todo.", en: "In the beginning of love there is a kind of madness that gives meaning to everything.", author: "Pablo Neruda", source: "Cien Sonetos de Amor" },
  { es: "El amor que vivimos fue el más largo de todos los instantes.", en: "The love we lived was the longest of all instants.", author: "Pablo Neruda", source: "Soneto LX" },
  { es: "Detrás de tu silencio hay una música que solo yo oigo.", en: "Behind your silence there is a music only I can hear.", author: "Pablo Neruda", source: "Soneto LXV" },
  { es: "Si el amor no duele, no es amor; es solo costumbre.", en: "If love does not hurt, it is not love; it is only habit.", author: "Octavio Paz", source: "Ladera Este" },
  { es: "Amor es el arco iris entre dos tormentas.", en: "Love is the rainbow between two storms.", author: "Octavio Paz", source: "Piedra de Sol" },
  { es: "Solo en el amor el tiempo se vuelve eternidad.", en: "Only in love does time become eternity.", author: "Octavio Paz", source: "Viento Entero" },
  { es: "Nos buscamos y nos encontramos y nos volvemos a buscar para siempre.", en: "We search for each other and find each other and search again, forever.", author: "Octavio Paz", source: "Piedra de Sol" },
  { es: "El amor perfecto no existe, pero existe el amor que perfecciona.", en: "Perfect love does not exist, but love that perfects does.", author: "Octavio Paz", source: "Libertad Bajo Palabra" },
  { es: "El amor llega sin llamar y se queda sin permiso.", en: "Love arrives without knocking and stays without permission.", author: "Jorge Luis Borges", source: "El Oro de los Tigres" },
  { es: "De todas las formas de caminar, la más hermosa es la que va hacia ti.", en: "Of all the ways of walking, the most beautiful is the one that goes toward you.", author: "Jorge Luis Borges", source: "El Hacedor" },
  { es: "El amor es la única realidad que no necesita ser explicada.", en: "Love is the only reality that needs no explanation.", author: "Jorge Luis Borges", source: "El Libro de Arena" },
  { es: "Te recordaré siempre, aunque se me olvide todo lo demás.", en: "I will always remember you, even if I forget everything else.", author: "Jorge Luis Borges", source: "La Memoria de Shakespeare" },
  { es: "La felicidad tiene el rostro de la persona que amamos.", en: "Happiness has the face of the person we love.", author: "Julio Cortázar", source: "Ultimo Round" },
  { es: "El amor no es un estado; es un viaje que no termina.", en: "Love is not a state; it is a journey that does not end.", author: "Julio Cortázar", source: "Prosa del Observatorio" },
  { es: "Besar es decir todo lo que las palabras no pueden decir.", en: "Kissing is saying everything that words cannot say.", author: "Julio Cortázar", source: "Rayuela" },
  { es: "El amor verdadero se reconoce por la paz que trae.", en: "True love is recognized by the peace it brings.", author: "Julio Cortázar", source: "Rayuela" },
  { es: "Si me amas, hazlo despacio, que las cosas que duran empiezan con calma.", en: "If you love me, do it slowly — things that last begin calmly.", author: "Julio Cortázar", source: "Rayuela" },
  { es: "El amor que no se dice en voz alta no desaparece; se hace más hondo.", en: "Love not said aloud does not disappear; it grows deeper.", author: "Juan Rulfo", source: "El Llano en Llamas" },
  { es: "El amor es el único camino que no necesita mapa.", en: "Love is the only road that needs no map.", author: "Juan Rulfo", source: "Pedro Páramo" },
  { es: "El amor es un fuego que alumbra sin consumirse.", en: "Love is a fire that lights without being consumed.", author: "Carlos Pellicer", source: "Hora de Junio" },
  { es: "Te llevo como el mar lleva a la luna: en mi vientre iluminado.", en: "I carry you as the sea carries the moon: in my illuminated belly.", author: "Carlos Pellicer", source: "Material Poético" },
  { es: "El amor nos hace habitar el presente.", en: "Love makes us inhabit the present.", author: "Eugenio Montejo", source: "Alfabeto del Mundo" },
  { es: "Vivir sin ti sería como un poema sin palabras.", en: "Living without you would be like a poem without words.", author: "Eugenio Montejo", source: "Alfabeto del Mundo" },
  { es: "El amor que conocí fue tan grande que no cabía en mí.", en: "The love I knew was so great it did not fit inside me.", author: "Eugenio Montejo", source: "Terredad" },
  { es: "Amar es la única aventura que vale el riesgo.", en: "To love is the only adventure worth the risk.", author: "Andrés Eloy Blanco", source: "Poda" },
  { es: "El amor sabe siempre a primera vez, aunque sea el último.", en: "Love always tastes like the first time, even when it is the last.", author: "Andrés Eloy Blanco", source: "Poda" },
  { es: "Tu nombre es la única contraseña de mi corazón.", en: "Your name is the only password of my heart.", author: "Vicente Gerbasi", source: "Mi Padre el Inmigrante" },
  { es: "El amor llega como la lluvia: sin previo aviso y empapa todo.", en: "Love arrives like rain: without warning and soaks everything.", author: "Vicente Gerbasi", source: "Los Espacios Cálidos" },
  { es: "Cuando te amo, el mundo tiene un centro y ese centro eres tú.", en: "When I love you, the world has a center and that center is you.", author: "Juan Sánchez Peláez", source: "Elena y los Elementos" },
  { es: "El amor es el idioma que aprendo en tu piel.", en: "Love is the language I learn in your skin.", author: "Juan Sánchez Peláez", source: "Elena y los Elementos" },
  { es: "Cada beso tuyo es el primer beso del mundo.", en: "Every kiss of yours is the first kiss in the world.", author: "Eunice Odio", source: "El Tránsito de Fuego" },
  { es: "Amo tu forma de existir, que hace que el mundo tenga forma.", en: "I love your way of existing, which gives shape to the world.", author: "Eunice Odio", source: "El Tránsito de Fuego" },
  { es: "El amor no se elige: nos elige.", en: "Love is not chosen: it chooses us.", author: "Roberto Juarroz", source: "Poesía Vertical" },
  { es: "Somos más que dos cuando nos amamos.", en: "We are more than two when we love each other.", author: "Roberto Juarroz", source: "Poesía Vertical" },
  { es: "Cada vez que te amo, invento un nuevo idioma.", en: "Each time I love you, I invent a new language.", author: "Roberto Juarroz", source: "Poesía Vertical" },
  { es: "El amor es la única forma de conocer el infinito.", en: "Love is the only way to know the infinite.", author: "Roberto Juarroz", source: "Poesía Vertical" },
  { es: "Amar es hacer eterno lo que dura un instante.", en: "To love is to make eternal what lasts an instant.", author: "Roberto Juarroz", source: "Poesía Vertical" },
  { es: "Cuando te miro, el azar parece tener un plan.", en: "When I look at you, chance seems to have a plan.", author: "Enrique Lihn", source: "La Pieza Oscura" },
  { es: "El amor es la única casa que no necesita techo.", en: "Love is the only house that needs no roof.", author: "Enrique Lihn", source: "Poesía de Paso" },
  { es: "Te amo con toda la torpeza de quien ama por primera vez y ya para siempre.", en: "I love you with all the clumsiness of one who loves for the first time and already forever.", author: "Enrique Lihn", source: "La Pieza Oscura" },
  { es: "El amor hace que el mundo sea menos extraño.", en: "Love makes the world less strange.", author: "Nicanor Parra", source: "Antipoemas" },
  { es: "No hay amor sin una dosis de locura.", en: "There is no love without a dose of madness.", author: "Nicanor Parra", source: "Antipoemas" },
  { es: "El amor es la única cosa seria que existe.", en: "Love is the only serious thing that exists.", author: "Nicanor Parra", source: "Canciones sin Nombre" },
  { es: "Amarte me ha costado todo, y lo daría todo otra vez.", en: "Loving you has cost me everything, and I would give it all again.", author: "Gonzalo Rojas", source: "La Miseria del Hombre" },
  { es: "El amor es el único milagro que no necesita testigos.", en: "Love is the only miracle that needs no witnesses.", author: "Gonzalo Rojas", source: "Contra la Muerte" },
  { es: "Solo el amor puede hacer del caos un jardín.", en: "Only love can turn chaos into a garden.", author: "Gonzalo Rojas", source: "Oscuro" },
  { es: "Amo tu manera de estar presente sin estar presente.", en: "I love your way of being present without being present.", author: "Gonzalo Rojas", source: "Oscuro" },
  { es: "El amor más puro nace de la herida más profunda.", en: "The purest love is born from the deepest wound.", author: "Fina García Marruz", source: "Visitaciones" },
  { es: "Amar es la única forma de no estar solos en el universo.", en: "Loving is the only way not to be alone in the universe.", author: "Fina García Marruz", source: "Las Miradas Perdidas" },
  { es: "Estoy hecho de ti y de lo que te falta.", en: "I am made of you and of what you lack.", author: "Eliseo Diego", source: "En la Calzada de Jesús del Monte" },
  { es: "El amor es el único camino de vuelta a uno mismo.", en: "Love is the only road back to oneself.", author: "Eliseo Diego", source: "Por los Extraños Pueblos" },
  { es: "Que el amor sea más fuerte que el miedo que le tenemos al amor.", en: "May love be stronger than the fear we have of love.", author: "Cintio Vitier", source: "Vísperas" },
  { es: "El amor es el único sistema que nunca falla.", en: "Love is the only system that never fails.", author: "Cintio Vitier", source: "Testimonios" },
  { es: "El amor llega a su máxima altura en el instante en que se convierte en ternura.", en: "Love reaches its highest point in the instant it becomes tenderness.", author: "Dulce María Loynaz", source: "Poemas sin Nombre" },
  { es: "Amo tus manos porque han tocado lo que más importa: mi corazón.", en: "I love your hands because they have touched what matters most: my heart.", author: "Dulce María Loynaz", source: "Poemas sin Nombre" },
  { es: "El amor es la única verdad que no necesita ser demostrada.", en: "Love is the only truth that needs no proof.", author: "Dulce María Loynaz", source: "Jardín" },
  { es: "Eres el nombre que mi silencio ha aprendido a pronunciar.", en: "You are the name my silence has learned to pronounce.", author: "Dulce María Loynaz", source: "Poemas sin Nombre" },
  { es: "El amor es el único horizonte que siempre se acerca.", en: "Love is the only horizon that always draws near.", author: "Heberto Padilla", source: "Fuera del Juego" },
  { es: "Cada caricia tuya es un acto de fe en la humanidad.", en: "Each caress of yours is an act of faith in humanity.", author: "Heberto Padilla", source: "El Justo Tiempo Humano" },
  { es: "El amor que más duele es el que nunca se dice.", en: "The love that hurts most is the one never spoken.", author: "Nancy Morejón", source: "Parajes de una Época" },
  { es: "Amar es dar tu nombre a quien más lo necesita.", en: "To love is to give your name to whoever needs it most.", author: "Nancy Morejón", source: "Octubre Imprescindible" },
];

export function poemForSeed(rng: () => number): Poem {
  return POEMS[Math.floor(rng() * POEMS.length)];
}
